name = input("Введите имя: ")
print("hello",name)
pause = input("Для продолжения нажмите любую клавишу")
age = input("Введите возраст: ")
print("Ваш возраст", age)
job = input("Место работы: ")
print = ("Ваше место работы: ", job)